# Generated by Django 3.0.10 on 2021-02-09 20:57

import apps.audios.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodocument',
            name='foi_transcrito',
        ),
        migrations.RemoveField(
            model_name='processedaudio',
            name='texto',
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='foi_processado',
            field=models.BooleanField(default=False, verbose_name='Foi Processado'),
        ),
        migrations.AddField(
            model_name='processedaudio',
            name='processor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Processador'),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='file',
            field=models.FileField(upload_to=apps.audios.models.audiodoc_directory_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição do Áudio'),
        ),
        migrations.AlterField(
            model_name='processedaudio',
            name='file_wc',
            field=models.FileField(upload_to=apps.audios.models.audiodoc_directory_path, verbose_name='Wordcloud'),
        ),
        migrations.CreateModel(
            name='LegendaTrecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField(verbose_name='Inicio Trecho')),
                ('end', models.FloatField(null=True, verbose_name='Fim Trecho')),
                ('text', models.TextField(default=None, null=True, verbose_name='Texto')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='audios.ProcessedAudio')),
            ],
        ),
    ]
