# Generated by Django 3.0.10 on 2021-01-13 21:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiodocument',
            options={'ordering': ('data_upload',), 'verbose_name': 'Audio', 'verbose_name_plural': 'Audios'},
        ),
        migrations.RenameField(
            model_name='audiodocument',
            old_name='description',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='audiodocument',
            name='document',
        ),
        migrations.RemoveField(
            model_name='audiodocument',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Atualização'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de Upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='doc',
            field=models.FileField(default=django.utils.timezone.now, upload_to='audio/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='foi_transcrito',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='transcricao',
            field=models.TextField(default=None, null=True),
        ),
    ]
