# Generated by Django 3.0.10 on 2021-01-19 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_auto_20210119_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedaudio',
            name='texto',
        ),
        migrations.CreateModel(
            name='LegendaTrecho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.FloatField(verbose_name='Inicio Trecho')),
                ('end', models.FloatField(verbose_name='Fim Trecho')),
                ('text', models.TextField(default=None, null=True, verbose_name='Texto')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='trechos', to='audios.ProcessedAudio')),
            ],
        ),
    ]
