# Generated by Django 3.0.10 on 2021-01-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_auto_20210119_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedaudio',
            name='processor',
            field=models.CharField(blank=True, max_length=255, verbose_name='Processador'),
        ),
    ]
