# Generated by Django 3.0.10 on 2021-01-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0003_auto_20210114_1942'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextoTranscrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcricao', models.TextField(default=None, null=True, verbose_name='Texto Transcrito')),
            ],
            options={
                'verbose_name': 'Texto Transcrito',
                'verbose_name_plural': 'Textos Transcritos',
                'ordering': ('transcricao',),
            },
        ),
        migrations.DeleteModel(
            name='TextDocument',
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='transcricao',
            field=models.TextField(default=None, null=True, verbose_name='Texto Transcrito'),
        ),
    ]
