# Generated by Django 3.0.10 on 2021-01-15 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0004_auto_20210114_2008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiodocument',
            old_name='doc',
            new_name='file',
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='size',
            field=models.BigIntegerField(null=True, verbose_name='Tamanho Arquivo'),
        ),
    ]
