# Generated by Django 3.0.10 on 2021-02-17 19:30

import apps.audios.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0004_audiodocument_processando'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedaudio',
            name='file_legenda',
            field=models.FileField(default=django.utils.timezone.now, upload_to=apps.audios.models.audiodoc_legenda_directory_path, verbose_name='Legenda'),
            preserve_default=False,
        ),
    ]
