# Generated by Django 3.0.10 on 2021-02-02 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0005_auto_20210120_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodocument',
            name='file',
            field=models.FileField(upload_to='audio/', verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='audiodocument',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição do Áudio'),
        ),
    ]
