# Generated by Django 3.0.10 on 2021-03-02 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0005_processedaudio_file_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodocument',
            name='api_user',
            field=models.IntegerField(null=True, verbose_name='ID do API User'),
        ),
        migrations.AddField(
            model_name='audiodocument',
            name='hashfile',
            field=models.CharField(max_length=255, null=True, verbose_name='Hash do Arquivo'),
        ),
    ]
