# Generated by Django 3.0.10 on 2021-02-08 20:08

import apps.audios.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0006_auto_20210202_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodocument',
            name='file',
            field=models.FileField(upload_to=apps.audios.models.user_directory_path, verbose_name='Arquivo'),
        ),
    ]
