# Generated by Django 3.0.10 on 2021-01-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='size',
            field=models.BigIntegerField(null=True, verbose_name='Tamanho Arquivo'),
        ),
    ]
