# Generated by Django 3.0.10 on 2021-02-09 20:57

import apps.docs.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='foi_transcrito',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='transcricao',
        ),
        migrations.AddField(
            model_name='textdocument',
            name='foi_processado',
            field=models.BooleanField(default=False, verbose_name='Foi Processado'),
        ),
        migrations.AlterField(
            model_name='cpfdata',
            name='cpf',
            field=models.CharField(blank=True, max_length=255, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cpfdata',
            name='pdoc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cpfs', to='docs.ProcessedText'),
        ),
        migrations.AlterField(
            model_name='processedtext',
            name='file_wc',
            field=models.FileField(upload_to=apps.docs.models.docs_directory_path, verbose_name='Wordcloud'),
        ),
        migrations.AlterField(
            model_name='processedtext',
            name='textdoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='processedtext', serialize=False, to='docs.TextDocument'),
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='file',
            field=models.FileField(upload_to=apps.docs.models.docs_directory_path, verbose_name='Arquivo'),
        ),
        migrations.AlterField(
            model_name='textdocument',
            name='nome',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descrição do Documento'),
        ),
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='TermoFreqData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=255, verbose_name='Termo')),
                ('qtd', models.IntegerField(blank=True, verbose_name='Qtd')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mais_frequentes', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=255, verbose_name='Telefone')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='E-Mail')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='CNPJData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=255, verbose_name='CNPJ')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cnpjs', to='docs.ProcessedText')),
            ],
        ),
    ]
