# Generated by Django 3.0.10 on 2021-01-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpfdata',
            name='pdoc',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cpfs', to='docs.ProcessedText'),
        ),
    ]
