# Generated by Django 3.0.10 on 2021-01-18 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_auto_20210118_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpfdata',
            name='cpf',
            field=models.CharField(blank=True, max_length=255, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='processedtext',
            name='textdoc',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='processedtext', serialize=False, to='docs.TextDocument'),
        ),
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='URL')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='TelefoneData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(blank=True, max_length=255, verbose_name='Telefone')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='EmailData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, verbose_name='E-Mail')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='docs.ProcessedText')),
            ],
        ),
        migrations.CreateModel(
            name='CNPJData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(blank=True, max_length=255, verbose_name='CNPJ')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cnpjs', to='docs.ProcessedText')),
            ],
        ),
    ]
