# Generated by Django 3.0.10 on 2021-02-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210210_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='processando',
            field=models.BooleanField(default=False, verbose_name='Processando'),
        ),
    ]
