# Generated by Django 3.0.10 on 2021-01-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_auto_20210118_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermoFreqData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('termo', models.CharField(blank=True, max_length=255, verbose_name='Termo')),
                ('qtd', models.IntegerField(blank=True, verbose_name='Qtd')),
                ('pdoc', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='mais_frequentes', to='docs.ProcessedText')),
            ],
        ),
    ]
