# Generated by Django 3.0.10 on 2021-01-19 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_termofreqdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='foi_transcrito',
        ),
        migrations.RemoveField(
            model_name='textdocument',
            name='transcricao',
        ),
        migrations.AddField(
            model_name='textdocument',
            name='foi_processado',
            field=models.BooleanField(default=False, verbose_name='Foi Processado'),
        ),
    ]
