# Generated by Django 3.0.10 on 2021-02-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_textdocument_processando'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='pandora_user',
            field=models.IntegerField(null=True, verbose_name='ID do Usuário Pandora'),
        ),
    ]
