# Generated by Django 3.0.10 on 2021-03-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0005_textdocument_pandora_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textdocument',
            name='pandora_user',
        ),
        migrations.AddField(
            model_name='textdocument',
            name='api_user',
            field=models.IntegerField(null=True, verbose_name='ID do API User'),
        ),
    ]
