# Generated by Django 3.0.10 on 2021-03-02 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20210301_1812'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textdocument',
            unique_together={('file', 'api_user')},
        ),
    ]
