# Generated by Django 3.0.10 on 2021-02-08 20:08

import apps.docs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0006_auto_20210203_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textdocument',
            name='file',
            field=models.FileField(upload_to=apps.docs.models.user_directory_path, verbose_name='Arquivo'),
        ),
    ]
