# Generated by Django 3.0.10 on 2021-03-02 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0007_auto_20210302_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='textdocument',
            name='hashfile',
            field=models.CharField(max_length=255, null=True, verbose_name='Hash do Arquivo'),
        ),
    ]
