# Generated by Django 3.0.10 on 2021-03-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0008_textdocument_hashfile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textdocument',
            unique_together={('hashfile', 'api_user')},
        ),
    ]
